language: erlang

env:
  - LUA=""
  - LUA="luajit"

install:
  - sudo apt-get install luajit

# "Build and test" this project. The important steps already happened
# in the install section!
script:
  - lua -v
  - type -p luarocks || true
