language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
    - os: linux
      sudo: false
      python: 3.5
    - os: osx
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip2 install pyflakes pycodestyle coverage coveralls nose --ignore-installed; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install pyflakes pycodestyle coverage coveralls nose; fi

script:
  - lua -v
  - type -p luarocks || true
