language: C

sudo: true

install:
        #- curl -R -O http://www.lua.org/ftp/lua-5.3.5.tar.gz
        #- tar zxf lua-5.3.5.tar.gz
        #- cd lua-5.3.5
        #- sudo -H make linux test install
        #- cd ..
   - git clone http://luajit.org/git/luajit-2.0.git
   - cd luajit-2.0; make && sudo make install
   - cd ..

script:
  - cd tests
  - luajit lib.lua
