language: C # does not really matter

env:
  - LUA=lua5.1
  - LUA=lua5.2
  - LUA=lua5.3
  - LUA=luajit2.0
  - LUA=luajit2.1

before_install:
  - source etc/install_lua.sh

script:
  - lua -v
  - type -p luarocks || true
